name = "MLKernels"
uuid = "48eadcf2-8ff1-11e8-289d-f103432a0bb3"
authors = ["trthatcher <trthatcher@users.noreply.github.com>"]
version = "0.4.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
